# Generated by Django 3.2 on 2021-04-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mskpv', '0003_auto_20210424_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
