# Generated by Django 3.2 on 2021-04-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mskpv', '0004_auto_20210425_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='Technology', max_length=225),
        ),
    ]
