# Generated by Django 3.2 on 2021-04-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mskpv', '0007_auto_20210427_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click link above to read more ...', max_length=225),
        ),
    ]
