# Generated by Django 3.2 on 2021-04-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mskpv', '0008_post_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default='Apr,28,2021'),
        ),
    ]
