# Generated by Django 3.2 on 2021-04-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mskpv', '0010_auto_20210428_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
