# Generated by Django 3.2 on 2021-05-04 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mskpv', '0014_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='dete_added',
            new_name='date_added',
        ),
    ]
