# Generated by Django 3.2 on 2021-05-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mskpv', '0019_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, default=models.CharField(max_length=225), max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=models.CharField(max_length=225),
        ),
    ]
