# Generated by Django 3.2 on 2021-05-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mskpv', '0020_auto_20210507_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=225),
        ),
    ]
