# Generated by Django 3.2 on 2021-05-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mskpv', '0023_auto_20210507_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
