# Generated by Django 3.2 on 2021-05-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mskpv', '0025_auto_20210516_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emailsubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_sub', models.EmailField(max_length=254)),
            ],
        ),
    ]
