# Generated by Django 3.2 on 2021-05-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mskpv', '0026_emailsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
        migrations.AlterField(
            model_name='emailsubscription',
            name='email_sub',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
