# Generated by Django 3.2 on 2021-05-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mskpv', '0027_auto_20210523_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsubscription',
            name='email_sub',
            field=models.EmailField(max_length=254),
        ),
    ]
