# Generated by Django 3.2 on 2021-05-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mskpv', '0028_alter_emailsubscription_email_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsubscription',
            name='email_sub',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
