# Generated by Django 3.2 on 2021-06-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mskpv', '0031_auto_20210523_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
